/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base-button.vue')['default']
    BaseSelect: typeof import('./src/components/base-select.vue')['default']
    BaseSpinner: typeof import('./src/components/base-spinner.vue')['default']
    BaseTable: typeof import('./src/components/base-table.vue')['default']
    BaseTextField: typeof import('./src/components/base-text-field.vue')['default']
    BaseTextInput: typeof import('./src/components/base-text-input.vue')['default']
    FileUploader: typeof import('./src/components/file-uploader.vue')['default']
    FloatingModal: typeof import('./src/components/floating-modal.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
